# Activated via SPRING_PROFILES_ACTIVE=local ]
# -- set that as a VM option or environment
# variable in the IntelliJ run configuration for local debugging.
#
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
server.port=${PSCOUT_PORT}