services:
  property-scout-manager:
    image: property-scout-manager:latest
    container_name: property-scout-manager
    env_file: .env
    environment:
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: support@oncoord.com
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      RECAPTCHA_SECRET_KEY: ${RECAPTCHA_SECRET_KEY}
      JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=75
    ports:
      - "127.0.0.1:${PSCOUT_PORT}:${PSCOUT_PORT}"
    mem_limit: 768m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - pgnet
    restart: unless-stopped

networks:
  pgnet:
    external: true
    name: property-scout-postgres_default